const contenuto = {
    0 :{  value: require("../Images/fiabe/192_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Pioggerella, pioggerella, dai, inizia a bagnare,",
      type:  "text"},
    2 :{  value: "gli ortaggi cresceranno, dopo noi li raccogliamo.",
      type:  "text"},
    3 :{  value: "Pioggerella, pioggerella, mettiti a innaffiare,",
      type:  "text", classe: "test"},
    4 :{  value: "di buon grano e farina noi il pane prepariamo.",
      type:  "text"},
    5:{  value: require("../Images/fiabe/192_02-img.png"),
      type:  "image", classe: 'imagemc'},
    6:{  value: "Pioggerella, pioggerella, vieni giù ancor più forte,",
      type:  "text"},
    7:{  value: "cresceranno i legumi, noi faremo delle scorte.",
      type:  "text"},
    8:{  value: "Raccogliamo poi i funghi che saranno nel boschetto,",
      type:  "text"},
    9:{  value: "e matura tanta frutta giù nel nostro giardinetto.",
      type:  "text"},
    10 :{  value: require("../Images/fiabe/192_03-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto