const contenuto = {
    0 :{  value: require("../Images/fiabe/274_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Una volpe camminava,",
      type:  "text"},
    2 :{  value: "una scarpa lei trovava,",
      type:  "text"},
    3 :{  value: "la scarpetta lei prendeva,",
      type:  "text", classe: "test"},
    4 :{  value: "al mercato la vendeva.",
      type:  "text"},
    5 :{  value: "No, aspetta, non vendeva,",
      type:  "text"},
    6 :{  value: "con un gallo la scambiava,",
      type:  "text"},
    7 :{  value: "poi col gallo barattava,",
      type:  "text"},
    8 :{  value: "paperella acquistava.",
      type:  "text"},
    9 :{  value: "Dopo l’oca lei comprava,",
      type:  "text"},
    10 :{  value: "con la papera scambiava.",
      type:  "text"},
    11 :{  value: "Commerciando la ochetta",
      type:  "text"},
    12 :{  value: "lei prendeva la capretta.",
      type:  "text"},
    13 :{  value: "La faccenda vale oro,",
      type:  "text"},
    14 :{  value: "dopo prende lei un toro.",
      type:  "text"},
    15 :{  value: "Un torello lazzarone,",
      type:  "text"},
    16 :{  value: "lei lo frusta col bastone:",
      type:  "text"},
    17 :{  value: "“Vai avanti mio torello,",
      type:  "text"},
    18 :{  value: "sei fortissimo e bello!”",
      type:  "text"},
    19 :{  value: require("../Images/fiabe/274_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto