const contenuto = {
    0 :{  value: require("../Images/fiabe/296_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Din-don! Din-don! Din-don!",
      type:  "text"},
    2 :{  value: "La campana sta suonando,",
      type:  "text"},
    3 :{  value: "e la casa sta bruciando,",
      type:  "text"},
    4 :{  value: "casa della nostra gatta",
      type:  "text"},
    5 :{  value: "oggi si è incendiata.",
      type:  "text"},
    6 :{  value: "Gatta fuori si è buttata,",
      type:  "text"},
    7 :{  value: "gli occhioni ha sgranato,",
      type:  "text"},
    8 :{  value: "col secchiello la gallina",
      type:  "text"},
    9 :{  value: "corre verso la gattina,",
      type:  "text"},
    10 :{  value: "col fanale il cavallino,",
      type:  "text"},
    11 :{  value: "con la scopa il cagnolino,",
      type:  "text"},
    12 :{  value: "corre anche il coniglio",
      type:  "text"},
    13 :{  value: "porta lui un po’ di tiglio.",
      type:  "text"},
    14 :{  value: "Uno, due, tre, acquetta,",
      type:  "text"},
    15 :{  value: "salva, salva la casetta!",
      type:  "text"},
    16 :{  value: require("../Images/fiabe/296_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto