const contenuto = {
    0 :{  value: require("../Images/fiabe/241_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Il leprotto sta saltando,",
      type:  "text"},
    2 :{  value: "le zampette sta sbattendo,",
      type:  "text"},
    3 :{  value: "lui così si sta scaldando,",
      type:  "text", classe: "test"},
    4 :{  value: "mentre il gelo sta venendo.",
      type:  "text"},
    5 :{  value: "Gli abeti sono bianchi,",
      type:  "text"},
    6 :{  value: "con la brina sono i pini,",
      type:  "text"},
    7 :{  value: "fa freddino ai fianchi,",
      type:  "text"},
    8 :{  value: "ci vorrebbero guantini.",
      type:  "text"},
    9 :{  value: "“E se fossi un contadino?”:",
      type:  "text"},
    10 :{  value: "sta pensando il leprotto,",
      type:  "text"},
    11 :{  value: "“Avrei messo il calzino,",
      type:  "text"},
    12 :{  value: "avrei messo il cappotto.",
      type:  "text"},
    13 :{  value: "Sarei stato in casetta",
      type:  "text"},
    14 :{  value: "con la mia coniglietta",
      type:  "text"},
    15 :{  value: "pasticcini a mangiare,",
      type:  "text"},
    16 :{  value: "al calduccio a svernare”.",
      type:  "text"},
  }

export default contenuto