const contenuto = {
    0 :{  value: require("../Images/fiabe/270_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Una piccola ranocchia",
      type:  "text"},
    2 :{  value: "nello stagno abitava,",
      type:  "text"},
    3 :{  value: "allenava le ginocchia,",
      type:  "text", classe: "test"},
    4 :{  value: "tutto il giorno lei saltava,",
      type:  "text"},
    5 :{  value: "carinissima ranocchia",
      type:  "text"},
    6 :{  value: "Raganella si chiamava.",
      type:  "text"},
    7 :{  value: "Tenta di saltar sul ponte,",
      type:  "text"},
    8 :{  value: "sbatte contro con la fronte,",
      type:  "text"},
    9 :{  value: "si rilancia inspirata,",
      type:  "text"},
    10 :{  value: "ma nel limo è cascata:",
      type:  "text"},
    11 :{  value: "coda sotto, il naso fuori,",
      type:  "text"},
    12 :{  value: "si dà spinta a strattoni,",
      type:  "text", classe: "test"},
    13 :{  value: "naso sotto, coda fuori,",
      type:  "text"},
    14 :{  value: "disperati suoi occhioni.",
      type:  "text"},
    15 :{  value: "Le amiche l’han cercata,",
      type:  "text"},
    16 :{  value: "le amiche l’han chiamata,",
      type:  "text"},
    17 :{  value: "ma la nostra Raganella",
      type:  "text"},
    18 :{  value: "sopra il ponte si è lanciata…",
      type:  "text"},
    19 :{  value: "(la storia riparte da capo)",
      type:  "text", classe: "spiegazione"},
    20 :{  value: require("../Images/fiabe/270_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto