const contenuto = {
    0 :{  value: require("../Images/fiabe/210_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Autunno, ti richiamiamo,",
      type:  "text"},
    2 :{  value: "autunno, ti invitiamo,",
      type:  "text"},
    3 :{  value: "vieni da noi a sostare",
      type:  "text", classe: "test"},
    4 :{  value: "i doni tuoi a portare:",
      type:  "text"},
    5 :{  value: "",
      type:  "text"},
    6 :{  value: "del grano dorato nell’aia,",
      type:  "text"},
    7 :{  value: "covoni di fieno e paglia,",
      type:  "text"},
    8 :{  value: "le piogge tuoi aspetteremo,",
      type:  "text"},
    9 :{  value: "le gru a partire vedremo.",
      type:  "text"},
    10:{  value: require("../Images/fiabe/210_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto