const contenuto = {
    0 :{  value: "Dalla nonna Melania",
      type:  "text"},
    1 :{  value: "Si sceglie il conduttore “Melania”. Bambini fanno il girotondo e recitando:",
      type:  "text", classe: 'box'},
    2 :{  value: require("../Images/fiabe/145_01-img.png"),
      type:  "image", classe: 'imagemc'},
    3 :{  value: "Da Melania, la vecchietta,",
      type:  "text"},
    4 :{  value: "nella piccola casetta,",
      type:  "text"},
    5 :{  value: "abitavan sette figli",
      type:  "text", classe: "test"},
    6 :{  value: "tutti senza sopraccigli,",
      type:  "text"},
    7 :{  value: "loro occhi son così,",
      type:  "text"},
    8 :{  value: "le orecchie son così,",
      type:  "text"},
    9 :{  value: "e * …. son così.",
      type:  "text"},
    10 :{  value: "Quelli non mangiavano,",
      type:  "text"},
    11 :{  value: "quelli la guardavano,",
      type:  "text"},
    12 :{  value: "tutto lor copiavano...",
      type:  "text"},
    13 :{  value: "*(inventano i giocatori)  “Melania” fa un movimento e tutti lo devono copiare. Chi non fa a tempo di fare l’imitazione diventa “Melania”.",
      type:  "text", classe: 'box'},
  }

export default contenuto