const contenuto = {
    0 :{  value: require("../Images/fiabe/154_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Si sta avvicinando il sonno,",
      type:  "text"},
    2 :{  value: "ti prende in braccio la nonna,",
      type:  "text"},
    3 :{  value: "facciamo un giro dal nonno,",
      type:  "text", classe: "test"},
    4 :{  value: "prendiamo un dolce rotondo.",
      type:  "text"},
    5 :{  value: require("../Images/fiabe/154_02-img.png"),
      type:  "image", classe: 'imagemc'},
    6 :{  value: "La mia amata bambina,",
      type:  "text"},
    7 :{  value: "carissima mia nipotina,",
      type:  "text"},
    8 :{  value: "si mette con me a dormire:",
      type:  "text"},
    9 :{  value: "“Gli occhi ormai non aprire”.",
      type:  "text"},
    10 :{  value: require("../Images/fiabe/154_03-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto