const contenuto = {
    0 :{  value: require("../Images/fiabe/132_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Il falco su’ volava",
      type:  "text"},
    2 :{  value: "e Anna lavorava,",
      type:  "text"},
    3 :{  value: "stivale lui perdeva",
      type:  "text", classe: "test"},
    4 :{  value: "e Anna sorrideva.",
      type:  "text"},
    5 :{  value: "Il falco le chiedeva",
      type:  "text"},
    6 :{  value: "passargli lo stivale",
      type:  "text"},
    7 :{  value: "e Anna gli diceva",
      type:  "text"},
    8 :{  value: "che non vedeva quale",
      type:  "text"},
    9 :{  value: "E poi lei aggiungeva",
      type:  "text"},
    10 :{  value: "che era impegnata,",
      type:  "text"},
    11 :{  value: "collana lei faceva",
      type:  "text", classe: "test"},
    12 :{  value: "ed era concentrata.",
      type:  "text"},
    13 :{  value: require("../Images/fiabe/132_03-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto