const contenuto = {
    0 :{  value: require("../Images/fiabe/195_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Pioggia, pioggia, vieni giù,",
      type:  "text"},
    2 :{  value: "vieni a bagnar di più!",
      type:  "text"},
    3 :{  value: "Vieni a bagnar la gente,",
      type:  "text", classe: "test"},
    4 :{  value: "sarà molto divertente!",
      type:  "text"},
    5 :{  value: "Fai sentire il tuo tuono,",
      type:  "text"},
    6 :{  value: "ascoltiamo questo suono.",
      type:  "text"},
    7 :{  value: "Porta l’acqua sana, pura,",
      type:  "text"},
    8 :{  value: "e innaffia la radura.",
      type:  "text"},
    9 :{  value: "Rasserena le giornate,",
      type:  "text"},
    10 :{  value: "fai venire qui l’estate.",
      type:  "text"},
    11 :{  value: require("../Images/fiabe/195_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto