const contenuto = {
    0 :{  value: require("../Images/fiabe/175_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Oche, oche",
      type:  "text"},
    2 :{  value: "I partecipanti al gioco sono: il padrone, le oche e il lupo; si mettono uno di fronte all’altro. Il padrone parla alle oche. Alle sue ultime parole le oche agitando le ali e corrono verso di lui. Il lupo le rincorre, finché non le prende tutte.",
      type:  "text", classe: 'box'},
    3 :{  value: "- Oche, oche.",
      type:  "text"},
    4 :{  value: "- Ga-ga-ga!",
      type:  "text"},
    5 :{  value: "- Fame avete?",
      type:  "text"},
    6 :{  value: "- Si, si sa’!",
      type:  "text"},
    7 :{  value: "- Su’ salite!",
      type:  "text"},
    8 :{  value: "- Non possiamo: c’è il lupo, lo temiamo. Ha dei denti affilati, vuol mangiare tutti quanti.",
      type:  "text"},
    9 :{  value: "- Ma le ali voi avete! O volate, o correte!",
      type:  "text"},
    10 :{  value: require("../Images/fiabe/175_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto