const contenuto = {
    0 :{  value: require("../Images/fiabe/189_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Cinciallegre sorelline,",
      type:  "text"},
    2 :{  value: "organetti fratellini,",
      type:  "text"},
    3 :{  value: "ehi, merlotti stornellini,",
      type:  "text", classe: "test"},
    4 :{  value: "anche i merli canterini!",
      type:  "text"},
    5 :{  value: "Arrivate voi dal mare",
      type:  "text"},
    6 :{  value: "primavera a portare!",
      type:  "text"},
    7 :{  value: "Con l’erbetta vellutata,",
      type:  "text"},
    8 :{  value: "con le perle di rugiada,",
      type:  "text"},
    9 :{  value: "con il caldo solicello,",
      type:  "text"},
    10 :{  value: "con un lieve venticello.",
      type:  "text"},
    11 :{  value: require("../Images/fiabe/189_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto