const contenuto = {
    0 :{  value: "“Gracchio nero sei tornato!",
      type:  "text"},
    1 :{  value: "Lì distante hai volato?",
      type:  "text"},
    2 :{  value: "Novità ci hai portato?",
      type:  "text", classe: "test"},
    3 :{  value: "Dai, raccontaci, alato!”",
      type:  "text"},
    4 :{  value: require("../Images/fiabe/118_01-img.png"),
      type:  "image", classe: 'imagemc'},
    5 :{  value: "“Son venuto alla saputa:",
      type:  "text"},
    6 :{  value: "l’erba verde è cresciuta;",
      type:  "text"},
    7 :{  value: "il cagnone è sulla paglia;",
      type:  "text", classe: "test"},
    8 :{  value: "l’orso il guinzaglio taglia;",
      type:  "text"},
    9 :{  value: require("../Images/fiabe/118_02-img.png"),
      type:  "image", classe: 'imagemc'},
    10 :{  value: "il padrone è a letto",
      type:  "text"},
    11 :{  value: "mette calze e il berretto;",
      type:  "text"},
    12 :{  value: "la padrona è ai fornelli",
      type:  "text", classe: "test"},
    13 :{  value: "fa bollire i tortelli,",
      type:  "text"},
    14 :{  value: "Masha e Kolia sta a chiamare,",
      type:  "text"},
    15 :{  value: "li invita a mangiare”.",
      type:  "text"},
    16 :{  value: require("../Images/fiabe/118_03-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto