const contenuto = {
    0 :{  value: require("../Images/fiabe/298_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Gatto grigio sul corbello,",
      type:  "text"},
    2 :{  value: "sta seduto dal cancello,",
      type:  "text"},
    3 :{  value: "la sua gatta lui aspetta,",
      type:  "text"},
    4 :{  value: "mentre lei non si affretta,",
      type:  "text"},
    6 :{  value: "guarda lei dalla finestra",
      type:  "text"},
    7 :{  value: "e prepara la minestra;",
      type:  "text"},
    8 :{  value: "sul terrazzo i gattini,",
      type:  "text"},
    9 :{  value: "i gattini-ragazzini,",
      type:  "text"},
    10 :{  value: "fanno i loro giochettini,",
      type:  "text"},
    11 :{  value: "mentre i cuccioli bambini",
      type:  "text"},
    12 :{  value: "a dormir sui tappetini.",
      type:  "text"},
    13 :{  value: "“Il più grande chi sarà?",
      type:  "text"},
    14 :{  value: "E il più piccolo?” “E mah!",
      type:  "text"},
    15 :{  value: "Tutti noi poi cresceremo,",
      type:  "text"},
    16 :{  value: "per i topi noi andremo;",
      type:  "text"},
    17 :{  value: "solo il nonno resterà",
      type:  "text"},
    18 :{  value: "e a casa dormirà",
      type:  "text"},
    19 :{  value: "sulla tiepida stufetta",
      type:  "text"},
    20 :{  value: "mentre altri lui aspetta”.",
      type:  "text"},
    21 :{  value: require("../Images/fiabe/298_02-img.png"),
      type:  "image", classe: 'imagemc'},
    
  }

export default contenuto