const contenuto = {
    0 :{  value: require("../Images/fiabe/135_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Per iniziare un gioco occorre chiamare a raccolta i partecipanti, recitando un «invito»; esempio:",
      type:  "text", classe: "box"},
    2 :{  value: "Ehi, venite a giocare",
      type:  "text"},
    3 :{  value: "ma dovete indovinare",
      type:  "text"},
    4 :{  value: "quale gioco noi facciamo,",
      type:  "text"},
    5 :{  value: "tutti quanti io vi chiamo,",
      type:  "text"},
    6 :{  value: "con i baffi le bambine,",
      type:  "text"},
    7 :{  value: "ragazzetti con treccine.",
      type:  "text"},
    8 :{  value: "Dopo di che con una conta si seleziona il “conduttore” del gioco. Nel caso al gioco partecipassero due squadre, il “conduttore” viene estratto a sorte. La selezione stessa diventa un “gioco prima del gioco”. Ecco come si potrebbe organizzare. Due bambini formano un “arco” prendendosi per le mani. Altri bambini si mettono in cerchio, formando un anello e passano sotto l’arco, recitando:",
      type:  "text", classe: "box"},
    9 :{  value: "Un porcello per boschetto",
      type:  "text"},
    10 :{  value: "gira e bruca il muschietto.",
      type:  "text"},
    11 :{  value: "Lo maciulla e lo bruca,",
      type:  "text"},
    12 :{  value: "poi lo mette nella buca.",
      type:  "text"},
    13 :{  value: "Ora chi è il “porcello”",
      type:  "text"},
    14 :{  value: "esca fuori dal “cancello”!",
      type:  "text"},
    15 :{  value: require("../Images/fiabe/135_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto