const contenuto = {
    0 :{  value: "Tutti fermi!",
      type:  "text"},
    1 :{  value: "La filastrocca può accompagnare sia il gioco da cortile, che il gioco del silenzio, che il gioco battimani e può essere anche usata come conta).",
      type:  "text", classe: 'box'},
    2 :{  value: require("../Images/fiabe/146_01-img.png"),
      type:  "image", classe: 'imagemc'},
    3 :{  value: "Il conduttore del gioco recita la filastrocca, tutti i giocatori girano liberamente, fanno dei movimenti liberi con le braccia, assumono varie posizioni del corpo. Alla parola “tutto si blocca!” ognuno si immobilizza nella posizione assunta al momento dell’esclamazione.",
      type:  "text", classe: 'box'},
    4 :{  value: "Cavallone, cavallone,",
      type:  "text"},
    5 :{  value: "noi stavamo sul balcone,",
      type:  "text", classe: "test"},
    6 :{  value: "del tè caldo prendevamo,",
      type:  "text"},
    7 :{  value: "i cucchiai suonavamo,",
      type:  "text"},
    8 :{  value: "e il turco parlavamo:",
      type:  "text"},
    9 :{  value: "“Ciabi-ciabi, albicocca.",
      type:  "text"},
    10 :{  value: "Misi l’acqua poi in bocca,",
      type:  "text"},
    11 :{  value: "tutto e tutti or si blocca!",
      type:  "text"},
    12 :{  value: "Chi per primo parlerà,",
      type:  "text"},
    13 :{  value: "una pigna beccherà”.",
      type:  "text"},
  }

export default contenuto