const contenuto = {
    0 :{  value: require("../Images/fiabe/288_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Albanella è un rapace,",
      type:  "text"},
    2 :{  value: "a cacciare è capace,",
      type:  "text"},
    3 :{  value: "per l’inverno fa la scorta,",
      type:  "text"},
    4 :{  value: "tutto in cantina porta:",
      type:  "text"},
    5 :{  value: require("../Images/fiabe/288_02-img.png"),
      type:  "image", classe: 'imagemc'},
    6 :{  value: "scarafaggi essiccati",
      type:  "text"},
    7 :{  value: "tutti ben impacchettati,",
      type:  "text"},
    8 :{  value: "le ranocchie marinate",
      type:  "text"},
    9 :{  value: "nella botte conservate,",
      type:  "text"},
    10 :{  value: "cosce dei maialini",
      type:  "text"},
    11 :{  value: "penzolano sui chiodini.",
      type:  "text"},
    12 :{  value: require("../Images/fiabe/288_03-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto