const contenuto = {
    0 :{  value: require("../Images/fiabe/203_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "",
      type:  "text"},
    2 :{  value: "",
      type:  "text"},
    3 :{  value: "",
      type:  "text", classe: "test"},
    4 :{  value: "",
      type:  "text"},
    5 :{  value: "",
      type:  "text"},
    6 :{  value: "",
      type:  "text"},
    7 :{  value: "",
      type:  "text"},
    8 :{  value: "",
      type:  "text"},
    9 :{  value: "",
      type:  "text"},
    10 :{  value: require("../Images/fiabe/203_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto