const contenuto = {
    0 :{  value: require("../Images/fiabe/219_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Il gelo è arrivato,",
      type:  "text"},
    2 :{  value: "steccato ha scavalcato,",
      type:  "text"},
    3 :{  value: "pupazzo lui ha creato,",
      type:  "text", classe: "test"},
    4 :{  value: "di neve bianca l’ha fatto.",
      type:  "text"},
    5 :{  value: "",
      type:  "text"},
    6 :{  value: "",
      type:  "text"},
    7 :{  value: "“Pupazzo, ehi, pupazzetto,",
      type:  "text"},
    8 :{  value: "il naso hai a gancetto,",
      type:  "text"},
    9 :{  value: "spetta che ci prepariamo,",
      type:  "text"},
    10 :{  value: "battaglia di neve facciamo!”",
      type:  "text"},
    11 :{  value: require("../Images/fiabe/219_02-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto