const contenuto = {
    0 :{  value: "Due allegre oche",
      type:  "text"},
    1 :{  value: require("../Images/fiabe/176_01-img.png"),
      type:  "image", classe: 'imagemc'},
    2 :{  value: "Stanno le ochette",
      type:  "text"},
    3 :{  value: "da una nonnetta",
      type:  "text"},
    4 :{  value: "una grigia,",
      type:  "text", classe: "test"},
    5 :{  value: "l’altra bianca,",
      type:  "text"},
    6 :{  value: "due allegrette.",
      type:  "text"},
    7 :{  value: "",
      type:  "text"},
    8 :{  value: "",
      type:  "text"},
    9 :{  value: "Tiran sù i colli,",
      type:  "text"},
    10 :{  value: "fanno i controlli",
      type:  "text"},
    11 :{  value: "“È più lungo!”",
      type:  "text"},
    12 :{  value: "“È più corto!”",
      type:  "text"},
    13 :{  value: "Stando giù nell’orto.",
      type:  "text", classe: "test"},
    14 :{  value: "",
      type:  "text"},
    15 :{  value: "",
      type:  "text"},
    16 :{  value: "Lavan le zampette",
      type:  "text"},
    17 :{  value: "queste due ochette,",
      type:  "text"},
    18 :{  value: "una grigia,",
      type:  "text"},
    19 :{  value: "l’altra bianca,",
      type:  "text"},
    20 :{  value: "cadon nel fossetto.",
      type:  "text"},
    21 :{  value: "",
      type:  "text"},
    22 :{  value: "",
      type:  "text", classe: "test"},
    23:{  value: "Piange la nonnina:",
      type:  "text"},
    24 :{  value: "“Mie ochettine!",
      type:  "text"},
    25 :{  value: "Una grigia,",
      type:  "text"},
    26 :{  value: "l’altra bianca,",
      type:  "text"},
    27 :{  value: "due poverine!”",
      type:  "text"},
    28 :{  value: "",
      type:  "text"},
    29 :{  value: "",
      type:  "text"},
    30 :{  value: "Poi le due ochette",
      type:  "text"},
    31 :{  value: "escon dal fossetto,",
      type:  "text"},
    32 :{  value: "una grigia,",
      type:  "text"},
    33 :{  value: "l’altra bianca,",
      type:  "text"},
    34 :{  value: "due allegrette.",
      type:  "text"},
  }

export default contenuto