const contenuto = {
    1 :{  value: "Sotto il portico d’oro",
      type:  "text"},
    2 :{  value: "stavano tutti costoro:",
      type:  "text"},
    3 :{  value: "",
      type:  "text", classe: "test"},
    4 :{  value: "",
      type:  "text"},
    5 :{  value: "lo zar e pur lo zarevič,",
      type:  "text"},
    6 :{  value: "Il re e poi сorolevič,",
      type:  "text"},
    7 :{  value: require("../Images/fiabe/137_02-img.png"),
      type:  "image", classe: 'imagemc'},
    8 :{  value: "il sarto, il calzolaio,",
      type:  "text"},
    9 :{  value: "e c’era pure il fornaio.",
      type:  "text"},
    10 :{  value: "E tu chi sarai,",
      type:  "text"},
    11 :{  value: "rispondi",
      type:  "text"},
    12 :{  value: "fallo in pochi secondi!",
      type:  "text"},
    13 :{  value: require("../Images/fiabe/137_03-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto