const contenuto = {
    0 :{  value: require("../Images/fiabe/163_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Fan così le paperette:",
      type:  "text"},
    2 :{  value: "“Kria-kria-kria! Kria-kria-kria!”",
      type:  "text"},
    3 :{  value: "E il verso di ochette:",
      type:  "text", classe: "test"},
    4 :{  value: "“Ga-ga-ga! Ga-ga-ga!”",
      type:  "text"},
    5 :{  value: "Il tacchino nel cortile:",
      type:  "text"},
    6 :{  value: require("../Images/fiabe/163_02-img.png"),
      type:  "image", classe: 'imagemc'},
    7 :{  value: "“Bal-bal-bal! Baldi-baldù!”",
      type:  "text"},
    8 :{  value: "I piccioni sull’ovile:",
      type:  "text"},
    9 :{  value: "“Gru-gru-gru, gru-gru-gru!”",
      type:  "text", classe: "test"},
    10 :{  value: "E i polli dal pollaio:",
      type:  "text"},
    11 :{  value: "“Co-co-co! Co-co-co!”",
      type:  "text"},
    12 :{  value: "Il galletto tutto gaio,",
      type:  "text"},
    13 :{  value: "sul recinto sale su",
      type:  "text", classe: "test"},
    14 :{  value: "al mattino presto, presto",
      type:  "text"},
    15 :{  value: "canta a noi: “Сu-ca-ri-cuuuuu!”",
      type:  "text"},
    16 :{  value: "I versi degli animali sono diversi da quelli italiani.",
      type:  "text", classe: "spiegazione"}, 
    17 :{  value: require("../Images/fiabe/163_03-img.png"),
      type:  "image", classe: 'imagemc'},
  }

export default contenuto