const contenuto = {
    0 :{  value: require("../Images/fiabe/134_01-img.png"),
      type:  "image", classe: 'imagemc'},
    1 :{  value: "Ogni riga della filastrocca va accompagnata con un movimento corrispondente.",
      type:  "text", classe: "box"},
    2 :{  value: "Dal signore lavoravo,",
      type:  "text"},
    3 :{  value: "poco, poco guadagnavo,",
      type:  "text"},
    4 :{  value: "ma avevo uno scopo,",
      type:  "text", classe: "test"},
    5 :{  value: "preso una slitta dopo.",
      type:  "text"},
    6 :{  value: "Slitta mia va da sola,",
      type:  "text"},
    7 :{  value: "va veloce, quasi vola;",
      type:  "text"},
    8 :{  value: "con la coda il vitello",
      type:  "text"},
    9 :{  value: "fa un girotondo bello;",
      type:  "text"},
    10 :{  value: "per il monte il capretto",
      type:  "text"},
    11 :{  value: "sale sul sentiero stretto;",
      type:  "text"},
    12 :{  value: require("../Images/fiabe/134_02-img.png"),
      type:  "image", classe: 'imagemc'},
    13 :{  value: "carinissima ochetta",
      type:  "text"},
    14 :{  value: "si risciacqua nell’acquetta;",
      type:  "text"},
    15 :{  value: "il tacchino fa: “glu-glu”,",
      type:  "text", classe: "test"},
    16 :{  value: "il gallo fa: “cu-ca-ri-cu”;",
      type:  "text"},
    17 :{  value: "e la mia paperetta",
      type:  "text"},
    18 :{  value: "se la spassa per l’erbetta;",
      type:  "text"},
    19 :{  value: "la gallina a passettini",
      type:  "text"},
    20 :{  value: "guida i piccoli pulcini,",
      type:  "text"},
    21 :{  value: "il signore sta a guardare,",
      type:  "text"},
    22 :{  value: "un sorriso grande a fare.",
      type:  "text"},
  }

export default contenuto